import type { PluginAPI } from '../types.js';
import type { HermesDB } from '../db/database.js';
import { Planner } from '../interview/planner.js';
import { Conductor } from '../interview/conductor.js';
import { text } from './helpers.js';

export function registerSessionTools(
  api: PluginAPI,
  db: HermesDB,
  planner: Planner,
  conductor: Conductor
): void {
  api.registerTool({
    name: 'hermes_session_plan',
    description: 'Create a new interview session for a job description and return the plan prompt for the LLM to generate an interview plan',
    parameters: {
      type: 'object' as const,
      properties: {
        jd_id: {
          type: 'string',
          description: 'ID of the job description to plan the session for',
        },
      },
      required: ['jd_id'],
    },
    execute: async (_id, params) => {
      const jdId = params.jd_id as string;

      const jd = db.getJobDescription(jdId);
      if (!jd) {
        return text({ content: '', error: `Job description ${jdId} not found.` });
      }

      const session = db.createSession(jdId);
      const prompt = planner.buildPlanPrompt(session.id);

      return text({
        content: `Session created.\nSession ID: ${session.id}\n\n${prompt}`,
      });
    },
  });

  api.registerTool({
    name: 'hermes_session_approve',
    description: 'Approve the interview plan for a session with the LLM-generated round list',
    parameters: {
      type: 'object' as const,
      properties: {
        session_id: {
          type: 'string',
          description: 'ID of the session to approve',
        },
        plan: {
          type: 'string',
          description: 'JSON array of interview rounds generated by the LLM',
        },
      },
      required: ['session_id', 'plan'],
    },
    execute: async (_id, params) => {
      const sessionId = params.session_id as string;
      const plan = params.plan as string;
      return text(planner.approvePlan(sessionId, plan));
    },
  });

  api.registerTool({
    name: 'hermes_session_status',
    description: 'Get the status of an interview session including rounds and scores',
    parameters: {
      type: 'object' as const,
      properties: {
        session_id: {
          type: 'string',
          description: 'ID of the session to check (defaults to the active session if omitted)',
        },
      },
    },
    execute: async (_id, params) => {
      let sessionId = params.session_id as string | undefined;

      if (!sessionId) {
        const active = db.getActiveSession();
        if (!active) {
          return text({ content: '', error: 'No active session found. Provide a session_id or start a new session.' });
        }
        sessionId = active.id;
      }

      return text(conductor.getSessionStatus(sessionId));
    },
  });
}
